<div class="container-fluid about">
	<h1>About the Live-Streams and Recordings</h1>
	<p>
		Lecture recording and streaming at 31st Chaos Communication Congress in Hamburg is organized and performed by a joint venture of <a href="http://fem.tu-ilmenau.de">Forschungsgemeinschaft elektronische Medien e.V.</a>, <a href="http://www.ags.tu-bs.de/">Wissenschaftliche Arbeitsgemeinschaft für Studio- und Senderfragen an der TU Braunschweig e.V.</a> and <a href="http://c3voc.de">Chaos Computer Club Video Operation Center</a>.
	</p>


	<h2>Licences</h2>
	<p>
		The video stream is licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">Attribution-ShareAlike 3.0</a>. This may not hold true for the slides or the actual performance. If in doubt please contact the speaker directly.
	</p>
	<p>
		Although the licence permits it, we would like to ask you to <strong>don't distribute stream dumps</strong>. We try to release finished cuts of recordings as quickly as possible on <a href="http://media.ccc.de/browse/congress/2014/index.html">media.ccc.de</a> and <a href="https://www.youtube.com/user/mediacccde">YouTube</a>. Early releases of incomplete stream dumps without audio translation, subtitles, intros, <a href="https://auphonic.com/">unprocessed audio</a> and missing meta data information is not what we have in mind when we spend three month of preparation in our spare time.
	</p>

	<h2>Privacy Policy</h2>
	<p>
		While browsing through the website normally we do not save any information wich could be used to identify a person. The log files are anonymized before they are saved and we do not have a de-anonymized version of the them. The anonymized log-files may be used to plot usage statistics.
	</p>

	<p>The following data is collected and saved for an undefined duration:</p>
	<ul>
		<li>date and time</li>
		<li>the visited pages</li>
		<li>status codes the webserver answered with</li>
		<li>your browser and operating system,</li>
		<li>and the referring URL</li>
	</ul>

	<p>
		If a connection to port 80 fails, an error log will be created. It contains the IP address of the host causing the error and the website containing the faulty hyperlink. This error log will only be used to fix the error and will not be used in any other way.
	</p>
	<p>
		Video and audio streams are provided by mirrors and are potentially not guaranteed to be covered by this policy.
	</p>

	<h2>Imprint</h2>
	<p>Please see <a href="//ccc.de/de/imprint">ccc.de</a>.</p>
</div>
