<div class="container-fluid about">
	<h1>About these awsome streams</h1>
	<p>
		Video and Audio Recording and Streaming on the 31st Chaos Communication Congress as well as on a lot of other Events during the is organized and performed by the c3voc, the <a href="//c3voc.de">CCC Video Operation Center</a>.
		We are a group of enthusiasts running lecture recording and streaming infrastructure. If you like to get in touch with us just ask on IRC in <a href="irc://irc.hackint.eu:6667/voc">#voc on hackint.eu</a>.
	</p>


	<h2>Licenses</h2>
	<p>
		The Streaming-Video is licensed under <a href="https://creativecommons.org/licenses/by-sa/3.0/">Attribution-ShareAlike 3.0</a>. This may not hold true for the slides or the actual performance. If in doubt please contact the speaker directly
	</p>

	<h2>Privacy Policy</h2>
	<p>
		While browsing through the website normally we do not save any information wich could be used to identify a person. The log files are anonymized before they are saved and we do not have a de-anonymized version of the them. The anonymized log-files may be used to plot usage statistics.
	</p>

	<p>The following data is collected and saved for an undefined duration:</p>
	<ul>
		<li>Date and time,</li>
		<li>the visited pages,</li>
		<li>status codes the webserver answered with,</li>
		<li>your browser and operating system,</li>
		<li>and the referring URL</li>
	</ul>

	<p>
		If a connection to port 80 fails, an error log will be created. It contains the IP address of the host causing the error and the website containing the faulty hyperlink. This error log will only be used to fix the error and will not be used in any other way.
	</p>
	<p>
		Video and audio files are often provided by mirrors and are not covered by this policy.
	</p>

	<h2>Imprint</h2>
	<p>Please see <a href="//ccc.de/de/imprint">ccc.de</a>.</p>
</div>
