<div class="container-fluid about">
	<h1>About the Live-Streams and Recordings</h1>
	<p>
		Lecture recording and streaming at 31st Chaos Communication Congress in Hamburg is organized and performed by a joint venture of <a href="http://fem.tu-ilmenau.de">Forschungsgemeinschaft elektronische Medien e.V.</a>, <a href="http://www.ags.tu-bs.de/">Wissenschaftliche Arbeitsgemeinschaft für Studio- und Senderfragen an der TU Braunschweig e.V.</a> and <a href="http://c3voc.de">Chaos Computer Club Video Operation Center</a>.
	</p>
	<p>
		If you like what we're doing, you can flattr us:<br /><br />
		<script id='fbleqbu'>(function(i){var f,s=document.getElementById(i);f=document.createElement('iframe');f.src='//api.flattr.com/button/view/?uid=c3voc&button=compact&url=http%3A%2F%2Fstreaming.media.ccc.de%2F';f.title='Flattr';f.height=20;f.width=110;f.style.borderWidth=0;s.parentNode.insertBefore(f,s);})('fbleqbu');</script>
	</p>


	<h2>Licences</h2>
	<p>
		The video stream is licensed under <a href="https://creativecommons.org/licenses/by/3.0/de/">CC Attribution 3.0 Germany (CC BY 3.0 DE)</a>. This may not hold true for the slides or the actual performance. If in doubt please contact the speaker directly.
	</p>
	<p>
		Although the licence permits it, we would like to ask you to <strong>don't distribute stream dumps</strong>. We try to release finished cuts of recordings as quickly as possible on <a href="http://media.ccc.de/browse/congress/2014/index.html">media.ccc.de</a> and <a href="https://www.youtube.com/user/mediacccde">YouTube</a>. Early releases of incomplete stream dumps without audio translation, subtitles, intros, <a href="https://auphonic.com/">unprocessed audio</a> and missing meta data is not what we have in mind when we spend three month of preparation in our spare time.
	</p>

	<h2>Privacy Policy</h2>
	<p>
		During 31C3, we'll log all accesses to this website
		(streaming.media.ccc.de) and the servers providing the video and audio
		streams. We do this to get an idea how the users are distributed though
		the internet, what streaming formats are popular and which players are
		used. We'll use this information for debugging during 31C3 and to
		optimize our streaming CDN configuration in the future.
	</p>

	<p>In particular, we collect the following data:</p>
	<ul>
		<li>your IP address</li>
		<li>date and time</li>
		<li>the visited page/stream</li>
		<li>status codes the servers answer with</li>
		<li>your browser/player and operating system</li>
		<li>the referring URL in case of HTTP</li>
	</ul>

	<p>
		Only statistical data which cannot be used to identify a person will be
		retained after <strong>2015-01-02</strong>. We'll destroy the original log files to the
		best of our knowledge and ability on that date.
	</p>
	<p>
		Beware that all of our CDN servers are donated by various entities. We
		cannot guarantee that (for example) their network infrastructure will
		comply to this policy.
	</p>

	<h2>Imprint</h2>
	<p>Please see <a href="//ccc.de/de/imprint">ccc.de</a>.</p>
</div>
