<div class="container about">
	<? if($conference->getTitle() != $next['name']): ?>
		<h1><?=h($conference->getTitle())?> is over!</h1>
	<? endif ?>

	<? if($next): ?>
		<h2>See you soon at <?=h($next['name'])?></h2>
		<span class="countdown" data-dt="<?=h($next['start_date'])?>"></span>
	<? endif ?>

	<p>
		Lecture recording and streaming at <strong><?=h($conference->getTitle())?></strong> was organized and performed by the <a href="http://c3voc.de">Chaos Computer Club Video Operation Center</a>. The next Events we'll attend will be
	</p>

	<br><br><br>

	<? foreach($events as $event): ?>
		<div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">

			<div class="panel panel-default">
				<div class="panel-heading">
					<? if($event['description']): ?>
						<a href="<?=h($event['description'])?>">
							<?=h($event['name'])?>
						</a>
					<? else: ?>
						<?=h($event['name'])?>
					<? endif ?>
				</div>
				<div class="panel-body">
					<?=h($event['location'])?><br />
					<?=h($event['start_date'])?> – <?=h($event['end_date'])?>
				</div>
			</div>

		</div>
	<? endforeach ?>
</div>
