<div class="container about">
	<h1><?=h($conference->getTitle())?> is over!</h1>

	<? if($upcoming): ?>
		<h2>See you soon at <?=h($upcoming['name'])?></h2>
	<? endif ?>

	<p>
		Lecture recording and streaming at <strong><?=h($conference->getTitle())?></strong> was organized and performed by the <a href="http://c3voc.de">Chaos Computer Club Video Operation Center</a>. The next Event we'll attend will be at
	</p>

	<br><br><br>

	<div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">

		<div class="panel panel-default">
			<div class="panel-heading"><?=h($upcoming['name'])?></div>
			<div class="panel-body">
				<?=h($upcoming['location'])?><br />
				<?=h($upcoming['start_date'])?> – <?=h($upcoming['end_date'])?>
			</div>
		</div>

	</div>
</div>
