<div class="container about">
	<? if ($next != null && $conference->getTitle() != $next['name']): ?>
		<h1><?=h($conference->getTitle())?> is over!</h1>
	<? endif ?>

	<? include("$assemblies/countdown.phtml") ?>

	<p>
		<? if($conference->hasReleases()): ?>
			Recordings will be released at <a href="<?=h($conference->getReleasesUrl())?>"><?=explode('?', h($conference->getReleasesUrl()))[0]?></a>.
		<? endif ?>

		<? if($conference->hasRelive()): ?>
			<? if($conference->hasReleases()): ?>
				Until all recordings are released, <a href="<?=h($conference->getReliveUrl())?>">ReLive</a> remains available.
			<? else: ?>
				You can still watch stream dumps <a href="<?=h($conference->getReliveUrl())?>">here</a>.
			<? endif ?>
		<? endif ?>

	</p>

	<p>
		Streaming at <strong><?=h($conference->getTitle())?></strong> was provided by the <a href="http://c3voc.de">Chaos Computer Club Video Operation Center</a>. The next events we'll attend will be
	</p>

	<br><br><br>

	<? include("$assemblies/upcoming.phtml") ?>
</div>
