<div class="container">
<h1><?=h($title)?></h1> <span><i>on <?= $hostname ?></i></span>
	<form action="<?=h($conference->getFeedbackReadUrl())?>" method="POST">

		<div class="row">
			<div class="col-xs-12">
				<div class="form-inline">

					<div class="form-group">
						<label class="sr-only" for="from">From Date</label>
						<div class="input-group">
							<div class="input-group-addon">From:</div>
							<input
								type="text"
								data-provide="datepicker"
								data-date-format="yyyy-mm-dd"
								data-date-week-start="1"
								data-date-today-btn="linked"
								data-date-today-highlight="true"
								class="form-control"
								name="from"
								id="from"
								value="<?=h(date('Y-m-d', $from))?>">
						</div>
					</div>

					<div class="form-group">
						<label class="sr-only" for="to">To Date</label>
						<div class="input-group">
							<div class="input-group-addon">To:</div>
							<input
								type="text"
								data-provide="datepicker"
								data-date-format="yyyy-mm-dd"
								data-date-week-start="1"
								data-date-today-btn="linked"
								data-date-today-highlight="true"
								class="form-control"
								name="to"
								id="to"
								value="<?=h(date('Y-m-d', $to))?>">
						</div>
					</div>

					<button type="submit" class="btn btn-primary">Filter</button>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-12">
				<div class="form-inline">
				<? foreach($allcolumns as $column): ?>
					<label class="checkbox-inline">
						<input
							type="checkbox"
							name="col[]"
							value="<?=h($column)?>"
							<? if(in_array($column, $columns)): ?>checked<? endif ?>
						> <?=h($column)?>
					</label>
				<? endforeach ?>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-xs-12">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<? foreach($columns as $column): ?>
								<th class="<?=h($column)?>"><?=h($column)?></th>
							<? endforeach ?>
						</tr>
					</thead>
					<tbody>
						<? foreach($responses as $response): ?>
							<tr>
								<? foreach($columns as $column): ?>
									<td class="<?=h($column)?>">
										<? if($column == 'reported' || $column == 'datetime'): ?>
											<?=h(date('Y-m-d H:i:s', $response[$column]))?>
										<? else: ?>
											<?=h($response[$column])?>
										<? endif ?>
									</td>
								<? endforeach ?>
							</tr>
						<? endforeach ?>
					</tbody>
				</table>
			</div>
		</div>

	</form>
</div>
