<? include("$assemblies/banner.phtml") ?>

<div class="container">
	<div class="row headline">
		<div class="col-xs-12">
			<h1><?=h($title)?></h1>
		</div>
	</div>

	<? $i = 0; foreach($overview->getGroups() as $group => $rooms): ?>
		<div class="row room-group room-group-n<?=h($i++)?>">
			<? if($group): ?>
				<div class="col-xs-12">
					<h2><?=h($group)?></h2>
				</div>
			<? endif ?>

			<? $count = count($rooms); ?>
			<? foreach($rooms as $idx => $room): ?>
				<div class="
					room
					room-<?=h($room->getSlug())?>
					clearfix

					<? /* when the count is odd and this is the last item - make it full width */ ?>
					<? if( ($count % 2 == 1) && ($idx == $count - 1) ): ?>
						wide
						col-xs-12
					<? else: ?>
						narrow
						<? if($room->hasPreview() && $room->hasSchedule()): ?>
							col-md-6
						<? else: ?>
							col-sm-6
						<? endif ?>
					<? endif ?>

					<? if($room->hasPreview()): ?>
						has-preview
					<? endif ?>

					<? if($room->hasSchedule()): ?>
						has-schedule
					<? endif ?>
				">

					<div class="panel panel-default">
						<div class="panel-heading">
							<div class="panel-title">
								<a href="<?=h($room->getLink())?>">
									<?=h($room->getDisplay())?>
								</a>
							</div>
						</div>

						<div class="panel-body">
							<? if($room->hasPreview()): ?>

								<a href="<?=h($room->getLink())?>">
									<img
										class="preview"
										src="<?=h($room->getThumb())?>"
										alt="<?=h($room->getDisplay())?>"
										width="213" height="120"
									/>
								</a>

							<? endif ?>

							<a href="<?=h($room->getLink())?>" class="title">
								<?=h($room->getDisplay())?>
							</a>

							<? if($room->hasSchedule()): ?>
								<div class="program-schedule">
									<div class="talk current-talk">
										<strong>Now:</strong>
										<span class="t">none</span>
									</div>

									<div class="talk next-talk">
										<strong>Next Talk:</strong>
										<span class="t">none</span>
									</div>
								</div>
							<? endif ?>
						</div>
					</div>
				</div>
			<? endforeach ?>
		</div>
	<? endforeach ?>

	<? if($conference->hasReleases() || $conference->hasRelive()): ?>
		<?
			$class = ($conference->hasReleases() && $conference->hasRelive()) ?
				// both enabled
				'col-sm-6 col-xs-12' :

				// only one of both enabled
				'col-xs-12';
		?>
		<div class="row recordings">

			<div class="col-xs-12">
				<h2>Recordings</h2>
			</div>

			<? if($conference->hasReleases()): ?>
				<div class="<?=h($class)?>">
					<div class="panel panel-primary">
						<div class="panel-body">
							<a href="<?=h($conference->getReleasesUrl())?>">
								<span class="fa fa-video-camera"></span> Releases
							</a>
						</div>
					</div>
				</div>
			<? endif ?>

			<? if($conference->hasRelive()): ?>
				<div class="<?=h($class)?>">
					<div class="panel panel-primary">
						<div class="panel-body">
							<a href="<?=h($conference->getReliveUrl())?>">
								<span class="fa fa-play-circle"></span> ReLive
							</a>
						</div>
					</div>
				</div>
			<? endif ?>

		</div>
	<? endif ?>
</div>
