<!DOCTYPE html>

<? if($conference->isPreviewEnabled()): ?>
<!--
  RUNNING IN PREVIEW MODE
  OPEN/CLOSED INFORMATION IS IGNORED!
-->
<? endif ?>

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv='X-UA-Compatible' content='IE=edge'>

<? include("$assemblies/motd.phtml") ?>

		<title><?=h($title)?> – <?=h($conference->getTitle())?> Streaming</title>

		<? if($conference->isPreviewEnabled()): ?>
			<meta name="robots" content="noindex,nofollow" />
		<? else: ?>
			<meta name="robots" content="index,follow" />
		<? endif ?>

		<? if(isset($refresh)): ?>
			<meta http-equiv="refresh" content="<?=h($refresh)?>; URL=<?=h($canonicalurl)?>" />
		<? endif ?>

		<? if($conference->hasAuthor()): ?>
			<meta name="author" content="<?=h($conference->getAuthor())?>" />
		<? endif ?>

		<? if($conference->hasDescription()): ?>
			<meta name="description" content="<?=h($conference->getDescription())?>" />
		<? endif ?>

		<? if($conference->hasKeywords()): ?>
			<meta name="keywords" content="<?=h($conference->getKeywords())?>" />
		<? endif ?>

		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="mobile-web-app-capable" content="yes" />
		<meta name="theme-color" content="#000000" />
		<meta name="apple-mobile-web-app-capable" content="yes" />

		<base href="<?=h($baseurl)?>" />
		<link href="<?=h($canonicalurl)?>" rel="canonical" />

		<link href="<?=h($assets)?>img/apple-touch-icon/57x57.png" rel="apple-touch-icon" sizes="57x57">
		<link href="<?=h($assets)?>img/apple-touch-icon/72x72.png" rel="apple-touch-icon" sizes="72x72">
		<link href="<?=h($assets)?>img/apple-touch-icon/60x60.png" rel="apple-touch-icon" sizes="60x60">
		<link href="<?=h($assets)?>img/apple-touch-icon/76x76.png" rel="apple-touch-icon" sizes="76x76">
		<link href="<?=h($assets)?>img/favicon/96x96.png" rel="icon" sizes="96x96" type="image/png">
		<link href="<?=h($assets)?>img/favicon/16x16.png" rel="icon" sizes="16x16" type="image/png">
		<link href="<?=h($assets)?>img/favicon/32x32.png" rel="icon" sizes="32x32" type="image/png">

		<link type="text/css" rel="stylesheet" href="<?=h($assets)?>mejs/mediaelementplayer.min.css" />
		<link type="text/css" rel="stylesheet" href="<?=h($conference_assets)?>gen/main.css" />

		<script type="text/javascript" src="<?=h($assets)?>js/lib/jquery.min.js"></script>
		<script type="text/javascript" src="<?=h($assets)?>js/lib/jquery.scrollTo.min.js"></script>
		<script type="text/javascript" src="<?=h($assets)?>js/lib/bootstrap.min.js"></script>
		<script type="text/javascript" src="<?=h($assets)?>js/lib/bootstrap-datepicker.min.js"></script>


		<? if (preg_match('@/cut$@', $_SERVER["REQUEST_URI"])): ?>
		<link href="<?=h($assets)?>netcut/lib/videojs/video-js.min.css" rel="stylesheet">
		<link href="<?=h($assets)?>netcut/lib/videojs-markers/videojs.markers.min.css" rel="stylesheet">
		<link href="<?=h($assets)?>netcut/assets/style.css" rel="stylesheet">
		<? else: ?>
		<script type="text/javascript" src="<?=h($assets)?>mejs/mediaelement-and-player.min.js"></script>
		<script type="text/javascript" src="<?=h($assets)?>voc-player/<?=$conference->get('PLAYER.VERSION') ?: 'player.js?v=1.3.1'?>"></script>
		<script type="text/javascript">window.Clappr = window.VOCPlayer</script>
		<script type="text/javascript" src="<?=h($assets)?>voc-player/clappr-thumbnails-plugin.js"></script>
		<script type="text/javascript" src="<?=h($assets)?>voc-player/clappr-playback-rate-plugin.js"></script>
		<script type="text/javascript" src="<?=h($assets)?>js/lustiges-script.js"></script>
		<script type="text/javascript" src="<?=h($assets)?>js/schedule.js"></script>

		<? endif ?>

		<? if(isset($subtitles) && $subtitles->isEnabled()): ?>
		<script type="text/javascript" src="<?=h($assets)?>js/lustige-subtitles.js"></script>
		<? endif ?>
	</head>
	<body class="<?=h(is_numeric($page[0]) ? 'e'.$page : $page)?>">
		<? if(!@$naked): ?>
			<? include("$assemblies/header.phtml") ?>
		<? endif ?>

		<? include("$page.phtml") ?>

		<? if(!@$naked): ?>
			<? include("$assemblies/footer.phtml") ?>
		<? endif ?>

		<? if(isset($schedule) && $schedule->isEnabled()): ?>
			<span class="js-schedule-settings"
				data-scheduleoffset="<?=h($schedule->getSimulationOffset())?>"
			></span>
		<? endif ?>
		<? if(isset($subtitles) && $subtitles->isEnabled()): ?>
			<span class="js-subtitles-settings"
				data-primus-url="<?=h($subtitles->getPrimusURL())?>"
				data-frontend-url="<?=h($subtitles->getFrontendURL())?>"
			></span>
		<? endif ?>


		<? if($page != 'allconferences' && $conference->hasAdditionalHtml()): ?>
			<?= $conference->getAdditionalHtml() ?>
		<? endif ?>
	</body>
</html>
