<!DOCTYPE html>

<? include('assemblies/motd.phtml') ?>

<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title><?=h($title)?> - 31C3 Streaming</title>

		<base href="<?=h($baseurl)?>" />
		<link type="text/css" rel="stylesheet" href="assets/css/lustige-styles.css" />
		<link type="text/css" rel="stylesheet" href="assets/css/lib/font-awesome.min.css" />
		<link type="text/css" rel="stylesheet" href="assets/css/lib/mediaelementplayer.min.css" />

		<script type="text/javascript" src="assets/js/jquery-1.8.3.min.js"></script>
		<script type="text/javascript" src="assets/js/lustiger-player.js"></script>
	</head>
	<body>
		<? include('assemblies/header.phtml') ?>
		<? include("$page.phtml") ?>
	</body>
</html>
