<!DOCTYPE html>


<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv='X-UA-Compatible' content='IE=edge'>

<? include("$assemblies/motd.phtml") ?>

		<title><?=h($title)?> – <?=h(get('CONFERENCE.TITLE', 'C3Voc'))?> Streaming</title>

		<meta name="robots" content="index,follow" />

		<? if(has('CONFERENCE.AUTHOR')): ?>
			<meta name="author" content="<?=h(get('CONFERENCE.AUTHOR'))?>" />
		<? endif ?>

		<? if(has('CONFERENCE.DESCRIPTION')): ?>
			<meta name="description" content="<?=h(get('CONFERENCE.DESCRIPTION'))?>" />
		<? endif ?>

		<? if(has('CONFERENCE.KEYWORDS')): ?>
			<meta name="keywords" content="<?=h(get('CONFERENCE.KEYWORDS'))?>" />
		<? endif ?>

		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<base href="<?=h($baseurl)?>" />
		<link href="<?=h($baseurl.ltrim($_SERVER['REQUEST_URI'], '/'))?>" rel="canonical" />

		<link href="assets/img/apple-touch-icon/76x76.png" rel="apple-touch-icon" />
		<link href="assets/img/apple-touch-icon/76x76.png" rel="apple-touch-icon" sizes="76x76" />
		<link href="assets/img/apple-touch-icon/72x72.png" rel="apple-touch-icon" sizes="72x72" />
		<link href="assets/img/apple-touch-icon/60x60.png" rel="apple-touch-icon" sizes="60x60" />
		<link href="assets/img/apple-touch-icon/57x57.png" rel="apple-touch-icon" sizes="57x57" />

		<link href="assets/img/favicon/196x196.png" rel="icon" type="image/png" />
		<link href="assets/img/favicon/196x196.png" rel="icon" type="image/png" sizes="196x196" />
		<link href="assets/img/favicon/96x96.png"   rel="icon" type="image/png" sizes="96x96"   />
		<link href="assets/img/favicon/32x32.png"   rel="icon" type="image/png" sizes="32x32"   />
		<link href="assets/img/favicon/16x16.png"   rel="icon" type="image/png" sizes="16x16"   />

		<link type="text/css" rel="stylesheet" href="assets/mejs/mediaelementplayer.min.css" />
		<link type="text/css" rel="stylesheet" href="assets/css/main.css" />

		<script type="text/javascript" src="assets/js/lib/jquery.min.js"></script>
		<script type="text/javascript" src="assets/js/lib/jquery.scrollTo.min.js"></script>
		<script type="text/javascript" src="assets/js/lib/bootstrap.min.js"></script>

		<script type="text/javascript" src="assets/mejs/mediaelement-and-player.min.js"></script>
		<script type="text/javascript" src="assets/js/lustiges-script.js"></script>
	</head>
	<body class="<?=h($page)?>">
		<? include("$assemblies/header.phtml") ?>
		<? include("$page.phtml") ?>
		<? include("$assemblies/footer.phtml") ?>

		<span class="js-settings"
			data-scheduleoffset="<?=h(get('SCHEDULE.OFFSET', 0))?>"
		></span>
	</body>
</html>
