<div class="container">
	<div class="row headline">
		<div class="col-xs-12">
			<h1><?=h($title)?></h1>
		</div>
	</div>

	<? if($talk['status'] == 'released'): ?>
		<div class="row">
			<div class="col-xs-12">
				<div class="alert alert-success">
					<h3>Released</h3>
					<p>This talk is already released! Take a look at <a href="<?=h($talk['release_url'])?>"><?=h(parse_url($talk['release_url'], PHP_URL_HOST))?></a>.</p>
				</div>
			</div>
		</div>
	<? endif ?>

	<? if(isset($talk['mp4'])): ?>
		<div class="row">
			<div class="col-xs-12">
				<div class="alert alert-success">
					<h3>Download</h3>
					<p>Click here to <a href="<?=h($talk['mp4'])?>">Download</a> this Relive-Recording. Beware! This is an unprocessed Streamdump – a final Release will follow soon.</p>
				</div>
			</div>
		</div>
	<? endif ?>

	<div class="row">
		<div class="col-xs-12">
			<div class="player-wrap">
				<? include("$assemblies/player/relive.phtml") ?>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-md-8 col-md-offset-2">
			<div class="well">
				<div class="desktop-player-hint">
					<h3>Sorry about the Flash</h3>
					<p>
						As there is no desktop player which supports time-shifting, we chose embed a Flash player here which does.
						If you still want to watch with a desktop player, use this URL: <a href="<?=h($talk['playlist'])?>"><?=h($talk['playlist'])?></a>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
