<div class="container">
	<div class="row headline">
		<div class="col-xs-12">
			<h1><?=h($title)?></h1>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12">
			<div class="player-wrap">
				<? include("$assemblies/player/relive.phtml") ?>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-xs-12 col-md-8 col-md-offset-2">
			<div class="well">
				<? include("$assemblies/desktop-player.phtml") ?>

				<? if($talk['status'] == 'released'): ?>
					<h3>Released</h3>
					<p>This talk is already released! Take a look at <a href="<?=h($talk['release_url'])?>">media.ccc.de</a>.</p>
				<? endif ?>
			</div>
		</div>
	</div>
</div>
