<div class="container-fluid">
	<h1>Experimetal ReLive Recordings</h1>

	<div class="event-previews">
		<h2 class="loading">Loading…</h2>

		<a class="event-preview template" href="url.html">
			<img alt="Readable Title" class="video-thumbnail" src="">
			<div class="caption">
				<ul class="metadata">
					<li>
						<span class="fa fa-clock-o"></span>
						36 min
					</li>
					<li>
						<span class="fa fa-calendar-o"></span>
						2013-12-28
					</li>
					<li class="persons">
						<span class="fa fa-user"></span>
						C B
					</li>
				</ul>
				<h3>Readable Title</h3>
			</div>
		</a>

	</div>
</div>
