<div class="container">
	<h1><?=h($title)?></h1>

	<div class="row">
		<div class="alert alert-danger" role="alert">
			<i class="fa fa-exclamation-circle"></i>
			<strong>Danger!</strong> Extreme Beta!!!
		</div>
	</div>

	<div class="event-previews relive">

		<? foreach ($talks as $talk): ?>
			<a class="event-preview <?=h($talk['status'])?>"
				<? if($talk['status'] == 'released'): ?>
					href="<?=h($talk['release_url'])?>"
				<? else: ?>
					href="<?=h(link_vod($talk['id']))?>"
				<? endif ?>
			>
				<img alt="<?=h($talk['title'])?>" class="video-thumbnail" src="http://vod.c3voc.de/relive/<?=h($talk['thumbnail'])?>">
				<div class="caption">
					<ul class="metadata">
						<li>
							<span class="fa fa-clock-o"></span>
							<?=h(round($talk['duration']/60))?> min
						</li>
						<li>
							<span class="fa fa-cogs"></span>
							<?=h($talk['status'])?>
						</li>
						<li>
							<span class="fa fa-sign-in"></span>
							<?=h($talk['room'])?>
						</li>
					</ul>
					<h3><?=h($talk['title'])?>
						<? if($talk['status'] == 'live'): ?>&nbsp;(Currently Live!)<? endif ?>
					</h3>
				</div>
			</a>
		<? endforeach ?>

	</div>
</div>
