<div class="container-fluid room <?=h($type)?> <?=h($format)?> <?=h($language)?>" data-room="<?=h($GLOBALS['CONFIG']['ROOMS'][$room])?>">
	<h1><?=h($title)?></h1>

	<ul class="nav nav-tabs nav-justified">
		<?
			if($miniroom)
				$tabs = array('video', 'audio');
			else
				$tabs = array('video', 'audio', 'slides');
		?>
		<? foreach($tabs as $iter): ?>
			<li
				<? if($type == $iter):?>class="active"<? endif ?>
			>
				<a href="<?=h(link_player($room, $iter))?>">
					<?=h(ucfirst($iter))?>
				</a>
			</li>
		<? endforeach ?>
	</ul>

	<div class="player-wrap">
		<? include("$assemblies/player/$type.phtml") ?>
	</div>

	<? if(!$miniroom): ?>
		<ul class="nav nav-tabs nav-justified" role="tablist">
			<li class="active">
				<a href="#switcher" role="tab" data-toggle="tab">Formats</a>
			</li>
			<li>
				<a href="#irc" role="tab" data-toggle="tab">IRC</a>
			</li>
			<li>
				<a href="#program" role="tab" data-toggle="tab">Program</a>
			</li>
		</ul>
	<? endif ?>

	<div class="tab-content">
		<div class="tab-pane active" id="switcher">

			<? if($miniroom): ?>
				<? include("$assemblies/switcher/miniroom-$type.phtml") ?>
			<? else: ?>
				<? include("$assemblies/switcher/$type.phtml") ?>
			<? endif ?>
		</div>
		<? if(!$miniroom): ?>
			<div class="tab-pane" id="irc">
				<? include("$assemblies/irc.phtml") ?>
			</div>
			<div class="tab-pane" id="program">
				<? include("$assemblies/program.phtml") ?>
			</div>
		<? endif ?>
	</div>
</div>
