<? include("$assemblies/banner.phtml") ?>

<div class="container-fluid rooms">
	<h1>Live-Streams</h1>

	<div class="room-group lecture" data-offset="<?=h($GLOBALS['CONFIG']['SCHEDULE_OFFSET'])?>">
		<h2>Lecture Rooms</h2>

		<ul class="row">
			<? foreach(array('saal1', 'saal2', 'saalg', 'saal6') as $room): ?>
				<li class="<?=h($room)?> col-sm-6">
					<a href="<?=h(link_room($room))?>">
						<div class="title"><?=h($rooms[$room])?></div>

						<div class="program-teaser">

							<span class="current-talk hidden">
								<strong>Current Talk:</strong>
								<span class="t">none</span>
							</span>

							<br />

							<span class="next-talk hidden">
								<strong>Next Talk:</strong>
								<span class="t">none</span>
							</span>
						</div>
					</a>
				</li>
			<? endforeach ?>
		</ul>
	</div>


	<div class="room-group">
		<h2>Live DJ Sets</h2>

		<ul class="row">
			<? foreach(array('lounge', 'ambient') as $room): ?>
				<li class="<?=h($room)?> col-sm-6">
					<a href="<?=h(link_room($room))?>" class="title"><?=h($rooms[$room])?></a>
				</li>
			<? endforeach ?>
		</ul>
	</div>


	<div class="room-group">
		<h2>Live Podcasts</h2>

		<ul class="row">
			<? foreach(array('sendezentrum') as $room): ?>
				<li class="<?=h($room)?> col-sm-12">
					<a href="<?=h(link_room($room))?>" class="title"><?=h($rooms[$room])?></a>
				</li>
			<? endforeach ?>
		</ul>
	</div>



	<div class="room-group">
		<h2>Recordings</h2>

		<ul class="row">
			<li class="recordings col-sm-12">
				<a href="//media.ccc.de/browse/congress/2014/index.html" class="title">Recordings</a>
			</li>
		</ul>
	</div>

</div>
