<div class="container <?=h($tab)?> <?=h($selection)?> <?=h($language)?>">
	<div class="row headline">
		<div class="col-xs-12">
			<h1 data-room="<?=h(get("ROOMS.$room.DISPLAY"))?>"><?=h($title)?></h1>
		</div>
	</div>

	<ul class="nav nav-player nav-tabs nav-justified">
		<? foreach($tabs as $iter): ?>
			<li
				<? if($tab == $iter):?>class="active"<? endif ?>
			>
				<a href="<?=h(link_player($room, $iter))?>">
					<?=h(ucfirst($iter))?>
				</a>
			</li>
		<? endforeach ?>
	</ul>

	<div class="player-wrap tab-content">
		<div class="tab-pane active">
			<? include("$assemblies/player/$tab.phtml") ?>
		</div>
	</div>

	<ul class="nav nav-functions nav-tabs nav-justified" role="tablist">
		<li class="active">
			<a href="#switcher" role="tab" data-toggle="tab">Formats</a>
		</li>
		<? if(get("ROOMS.$room.IRC") && has("IRC")): ?>
			<li>
				<a href="#irc" role="tab" data-toggle="tab">IRC</a>
			</li>
		<? endif ?>
		<? if(get("ROOMS.$room.SCHEDULE") && has("SCHEDULE")): ?>
			<li>
				<a href="#program" role="tab" data-toggle="tab">Program</a>
			</li>
		<? endif ?>
		<? if(get("ROOMS.$room.FEEDBACK") && has("FEEDBACK")): ?>
			<li>
				<a href="#feedback" role="tab" data-toggle="tab">Feedback</a>
			</li>
		<? endif ?>
	</ul>

	<div class="functions-wrap tab-content">
		<div class="tab-pane active" id="switcher">
			<? include("$assemblies/switcher/$tab.phtml") ?>
		</div>
		<? if(get("ROOMS.$room.SCHEDULE") && has("SCHEDULE")): ?>
			<div class="tab-pane" id="irc">
				<? include("$assemblies/irc.phtml") ?>
			</div>
		<? endif ?>
		<? if(get("ROOMS.$room.FEEDBACK") && has("FEEDBACK")): ?>
			<div class="tab-pane" id="program">
				<? include("$assemblies/program.phtml") ?>
			</div>
		<? endif ?>
		<? if(get("ROOMS.$room.FEEDBACK") && has("FEEDBACK")): ?>
			<div class="tab-pane" id="feedback">
				<? include("$assemblies/feedback.phtml") ?>
			</div>
		<? endif ?>
	</div>
</div>
