<div class="container <?=h($stream->getTab())?> <?=h($stream->getSelection())?> <?=h($stream->getLanguage())?>">
	<div class="row headline">
		<div class="col-xs-12">
			<h1 data-room="<?=h($room->getDisplay())?>"><?=h($stream->getDisplay())?></h1>
		</div>
	</div>

	<ul class="nav nav-player nav-tabs nav-justified">
		<? foreach($room->getTabs() as $tab): ?>
			<li
			    <? // The video tab can also be hls, so we need to check for that too ?>
				<? if($tab->getTab() == $stream->getTab() || ($tab->getTab() == 'dash' && $stream->getTab() == 'hls')): ?>class="active"<? endif ?>
			>
				<a href="<?=h($tab->getLink())?>">
					<?=h($tab->getDisplay())?>
				</a>
			</li>
		<? endforeach ?>
	</ul>

	<div class="player-wrap tab-content">
		<div role="tabpanel" class="tab-pane active">
			<? require("$assemblies/player/".$stream->getPlayerType().".phtml") ?>
		</div>
	</div>

	<ul class="nav nav-functions nav-tabs nav-justified" role="tablist">
		<? if($room->hasSchedule()): ?>
			<li class="active">
				<a href="#schedule" role="tab" data-toggle="tab">Fahrplan</a>
			</li>
		<? endif ?>
		<li <? if (! $room->hasSchedule()): ?>class="active"<? endif ?>>
			<a href="#switcher" role="tab" data-toggle="tab">Formats</a>
		</li>
		<? if($room->hasChat()): ?>
			<li>
				<a href="#chat" role="tab" data-toggle="tab">Chat</a>
			</li>
		<? endif ?>
		<? if($room->hasFeedback()): ?>
			<li>
				<a href="#feedback" role="tab" data-toggle="tab">Feedback</a>
			</li>
		<? endif ?>
		<? if($room->hasEmbed()): ?>
			<li>
				<a href="#embed" role="tab" data-toggle="tab">Embed</a>
			</li>
		<? endif ?>
		<? if($room->hasInfo()): ?>
			<li>
				<a href="#info" role="tab" data-toggle="tab">Info</a>
			</li>
		<? endif ?>
	</ul>

	<div class="functions-wrap tab-content">
		<? if($room->hasSchedule()): ?>
			<div role="tabpanel" class="tab-pane active" id="schedule">
				<? require("$assemblies/schedule.phtml") ?>
			</div>
		<? endif ?>
		<div role="tabpanel" class="tab-pane<? if (! $room->hasSchedule()): ?> active<? endif ?>"
			id="switcher">
			<? require("$assemblies/switcher/".$stream->getPlayerType().".phtml") ?>
		</div>
		<? if($room->hasChat()): ?>
			<div role="tabpanel" class="tab-pane" id="chat">
				<? require("$assemblies/chat.phtml") ?>
			</div>
		<? endif ?>
		<? if($room->hasFeedback()): ?>
			<div role="tabpanel" class="tab-pane" id="feedback">
				<? require("$assemblies/feedback.phtml") ?>
			</div>
		<? endif ?>
		<? if($room->hasEmbed()): ?>
			<div role="tabpanel" class="tab-pane" id="embed">
				<? require("$assemblies/embed-form.phtml") ?>
			</div>
		<? endif ?>
		<? if($room->hasInfo()): ?>
			<div role="tabpanel" class="tab-pane" id="info">
				<? require("$assemblies/info.phtml") ?>
			</div>
		<? endif ?>
	</div>
</div>
