<? if($room->hasIrc()): ?>
	<div>
		<a class="btn btn-primary irclink" href="<?=h($room->getIrcUrl())?>" target="_blank">
			<span class="fa fa-comment"></span> <?=h($room->getIrcDisplay())?>
		</a>
	</div>
<? endif ?>

<? if($room->hasTwitter($room)): ?>
	<div>
		<a class="btn twitterlink" href="<?=h($room->getTwitterUrl())?>" target="_blank">
			<span class="fa fa-twitter"></span> <?=h($room->getTwitterDisplay())?>
		</a>
	</div>
<? endif ?>
