<div class="desktop-player-hint">
	<h3>Use a desktop player!</h3>
	<p>Browsers and video doesn't go together well, even in <?=h(date('Y'))?> and especially when it's live. So for your best viewing experience please use a desktop player like VLC or mplayer.</p>
	<p>Beware that downloading the HLS playlist file is useless because of the way HLS works. You need to play the URL from your player.</p>
</div>
