<form action="feedback/" target="feedback-target" method="post" role="form" class="feedback-form">
	<div class="col-sm-4 col">
		<div class="form-group">
			<label for="net">Network Connection</label>
			<select class="form-control" name="net" id="net">
				<option></option>
				<option>EDGE</option>
				<option>3G</option>
				<option>LTE</option>
				<option>DSL &lt;2000</option>
				<option>DSL 2000-6000</option>
				<option>DSL &gt;6000</option>
				<option>VDSL</option>
				<option>Public Hotspot</option>
				<option>WLAN Inside the CCH</option>
				<option>Ethernet Inside the CCH</option>
				<option>Something else</option>
			</select>
		</div>

		<div class="form-group">
			<label for="os">Operating System</label>
			<select class="form-control" name="os" id="os">
				<option></option>
				<option>Unixoid</option>
				<option>OS/X</option>
				<option>Windows</option>
				<option>iOS</option>
				<option>Android</option>
				<option>Something else</option>
			</select>
		</div>

		<div class="form-group">
			<label for="player">Player</label>
			<select class="form-control" name="player" id="player">
				<option></option>
				<option>Firefox</option>
				<option>Chrome/Chromium</option>
				<option>Safari</option>
				<option>VLC</option>
				<option>MPlayer</option>
				<option>Totem</option>
				<option>ffplay</option>
				<option>iOS</option>
				<option>Android</option>
				<option>Something else</option>
			</select>
		</div>

		<div class="form-group">
			<label for="stream">Stream</label>
			<select class="form-control" name="stream" id="stream">
				<option></option>
				<? foreach(Room::rooms() as $roomiter): ?>
					<? if(!$roomiter->hasFeedback()) continue ?>
					<? foreach($roomiter->getSelections() as $selection): ?>
						<option
							<? if(
								isset($room) && isset($stream) &&
								$roomiter->getSlug() == $room->getSlug() &&
								$selection->getSelection() == $stream->getSelection()
							): ?>selected<? endif ?>
							value="<?=h($roomiter->getSlug().'-'.$selection->getSelection())?>"
						>
							<?=h($roomiter->getDisplay())?> – <?=h($selection->getDisplay())?>
						</option>
					<? endforeach ?>
				<? endforeach ?>
			</select>
		</div>
	</div>

	<div class="col-sm-4 col">
		<div class="form-group">
			<label>IP-Connectivity</label>
			<div class="checkbox">
				<label>
					<input type="checkbox" value="v4" name="ipproto[]" /> IPv4
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" value="v6" name="ipproto[]" /> IPv6
				</label>
			</div>
		</div>

		<div class="form-group">
			<label for="datetime">Date/Time</label>
			<input type="text" value="<?=h(strftime('%d.%m.%Y %H:%I'))?>" name="datetime" id="datetime" class="form-control" />
		</div>

		<div class="form-group">
			<label for="provider">Provider</label>
			<input type="text" value="" name="provider" id="provider" class="form-control" />
		</div>
	</div>

	<div class="col-sm-4 col">
		<div class="form-group">
			<label>Did you have Issues?</label>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="issues[]" value="Dropouts" /> Dropouts
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="issues[]" value="Hickups/Jerking" /> Hickups/Jerking
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="issues[]" value="Loops" /> Loops
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="issues[]" value="No Image" /> No Image
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="issues[]" value="No Audio" /> No Audio
				</label>
			</div>
			<div class="checkbox">
				<label>
					<input type="checkbox" name="issues[]" value="Artifacts" /> Artifacts
				</label>
			</div>
		</div>

		<div class="form-group">
		<label for="issuetext">Something else was good/bad</label>
			<input type="text" value="" name="issuetext" id="issuetext" class="form-control" />
		</div>

		<div class="form-group">
			<input class="btn btn-primary" type="submit" value="Submit" />
		</div>
	</div>
</form>

<h3 class="feedback-thankyou">Thank you!</h3>
<h3 class="feedback-error">The Feedback seems to be also broken…</h3>
<iframe name="feedback-target" style="display: none;"></iframe>
