<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="">
				<i class="icon"></i>
				<?=h($conference->getTitle())?> Streaming
			</a>
		</div>

		<div class="nav navbar-form navbar-right button-wrapper">
			<? if(startswith('//', @$GLOBALS['CONFIG']['BASEURL'])): ?>
				<a class="form-control btn btn-ssl btn-<?= ssl() ? 'success' : 'warning' ?>" href="<?=h(ssl() ? $httpurl : $httpsurl)?>">
					<span class="fa fa-<?= ssl() ? 'lock' : 'unlock-alt' ?>"></span>
					TLS
				</a>
			<? endif ?>

			<? if(!$conference->hasEnded() && isset($feedback) && $feedback->isEnabled()): ?>
				<a class="form-control btn btn-default feedback" href="<?=h($feedback->getUrl())?>">
					<span class="fa fa-bullhorn"></span>
				</a>
			<? endif ?>
			<? if($conference->hasReleases()): ?>
				<a class="form-control btn btn-default releases" href="<?=h($conference->getReleasesUrl())?>">
					<span class="fa fa-video-camera"></span>
				</a>
			<? endif ?>
			<a class="form-control btn btn-default about" href="about/">
				<span class="fa fa-info"></span>
			</a>
		</div>
	</div>
</nav>


<? if($conference->isPreviewEnabled()): ?>
<div class="preview-warning">
	PREVIEW MODE
</div>
<? endif ?>