<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="index.html">
				<img alt="ccc-tv logo, a tv displaying a play icon" src="assets/img/tv.png">
				ccc-tv
			</a>
		</div>

		<div class="nav navbar-form navbar-right button-wrapper">
			<a class="form-control btn btn-default" href="podcast.xml">
				<span class="fa fa-rss"></span>
			</a>
			<a class="form-control btn btn-default" href="about.html">
				<span class="fa fa-info"></span>
			</a>
		</div>

		<form action="/search/" class="navbar-form navbar-right" id="media-search" method="get" role="search">
			<div class="form-group input-group">
				<input class="form-control" name="q" placeholder="Search…" size="17" type="search">
				<span class="input-group-btn">
					<button class="btn btn-default" type="submit">
					<span class="fa fa-search"></span>
				</button>
				</span>
			</div>
		</form>

	</div>
</div>
