<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="">
				<i class="icon"></i>
				<?=h($conference->getTitle())?>
			</a>
		</div>

		<div class="nav navbar-form navbar-right button-wrapper">
			<? if($feedback->isEnabled()): ?>
				<a class="form-control btn btn-default" href="<?=h($feedback->getUrl())?>">
					<span class="fa fa-bullhorn"></span>
				</a>
			<? endif ?>
			<? if($conference->hasReleases()): ?>
				<a class="form-control btn btn-default" href="<?=h($conference->getReleasesUrl())?>">
					<span class="fa fa-video-camera"></span>
				</a>
			<? endif ?>
			<a class="form-control btn btn-default" href="about/">
				<span class="fa fa-info"></span>
			</a>
		</div>
	</div>
</nav>
