<?

foreach(reset($program) as $event)
	$width += $event['duration'];

?>
<div class="program scroll-container" data-offset="<?=h($GLOBALS['CONFIG']['SCHEDULE_OFFSET'])?>">
	<div class="scroll-element">
		<div class="now"><span>now</span></div>
		<? foreach($program as $name => $events): ?>
			<div class="room" style="width: <?=$width * $GLOBALS['CONFIG']['SCHEDULE_SCALE'] ?>px">
				<? foreach($events as $event): ?>

					<div
						class="block <?=h(@$event['special'] ?: 'event')?>"
						style="width: <?=h($event['duration'] * $GLOBALS['CONFIG']['SCHEDULE_SCALE'])?>px"
						data-start="<?=intval($event['start'])?>"
						data-end="<?=intval($event['end'])?>"
					>
						<? if(@$event['special'] == 'daychange'): ?>

							<h3><?=h($event['title'])?></h3>

						<? elseif(@$event['special'] == 'gap'): ?>

							<!--h3>Gap</h3-->

						<? elseif(@$event['special'] == 'pause'): ?>

							<h3><?=h($event['title'])?></h3>

						<? else: ?>

							<h4><?=h(strftime('%H:%M', $event['start']))?>&nbsp;&ndash;&nbsp;<?=h(strftime('%H:%M', $event['end']))?></h4>
							<h3><?=h($event['title'])?></h3>

						<? endif ?>
					</div>

				<? endforeach ?>
			</div>
		<? endforeach ?>
	</div>
</div>
