<?

foreach(reset($program) as $event)
	$width += $event['duration'];

?>
<div class="program scroll-container">
	<div class="scroll-element">
		<div class="now"><span>now</span></div>
		<? foreach($program as $name => $events): ?>
			<div class="room <? if($name == get("ROOMS.$room.SCHEDULE_NAME", $room)): ?>highlight<? endif ?>" style="width: <?=$width / get('SCHEDULE.SCALE')?>px">
				<? foreach($events as $event): ?>

					<div
						class="block <?=h(@$event['special'] ?: 'event')?>"
						style="width: <?=h($event['duration'] / get('SCHEDULE.SCALE'))?>px"
						data-start="<?=intval($event['start'])?>"
						data-end="<?=intval($event['end'])?>"
					>
						<? if(@$event['special'] == 'daychange'): ?>

							<h3><?=h($event['title'])?></h3>

						<? elseif(@$event['special'] == 'gap'): ?>

							<!--h3>Gap</h3-->

						<? elseif(@$event['special'] == 'pause'): ?>

							<h3><?=h($event['title'])?></h3>

						<? else: ?>

							<h4><?=h(strftime('%H:%M', $event['start']))?>
								&ndash;
								<?=h(strftime('%H:%M', $event['end']))?>
								&nbsp;in&nbsp;
								<a href="<?=h(link_player($room))?>">
									<?=h(get("ROOMS.$room.DISPLAY"))?>
								</a>
							</h4>
							<h3>
								<a
									href="<?=h(link_player($room))?>"
									title="Switch to <?=h(get("ROOMS.$room.DISPLAY"))?>"
								><?=h($event['title'])?></a>
							</h3>
							<h5>by&nbsp;<?=h($event['speaker'])?></h5>
						<? endif ?>
					</div>

				<? endforeach ?>
			</div>
		<? endforeach ?>
	</div>
</div>
