<div class="schedule scroll-container">
	<div class="scroll-element">
		<div class="now"><span>now</span></div>
		<? $rooms = $schedule->getSchedule() ?>
		<? foreach($rooms as $roomname => $events): ?>
			<div class="room <? if(isset($room) && $roomname == $room->getSlug()): ?>highlight<? endif ?>" style="width: <?=round($schedule->getDurationSum() / $schedule->getScale())?>px">
				<? $fromstart = 0; ?>
				<? foreach($events as $event): ?>
					<div
						class="block <?=h(@$event['special'] ?: 'event')?>"
						style="width: <?=h(round($event['duration'] / $schedule->getScale()))?>px; left: <?=h(round($fromstart / $schedule->getScale()))?>px"
						data-start="<?=intval($event['start'])?>"
						data-end="<?=intval($event['end'])?>"
					>
						<? $fromstart += $event['duration'] ?>
						<? $scheduleRoom = Room::createIfExists($roomname) ?>
						<? if($scheduleRoom): ?>
							<a
								class="inner"
								href="<?=h($scheduleRoom->createTabObject()->getLink($roomname))?>"
								title="Switch to <?=h($scheduleRoom->getDisplay())?>"
							>
						<? else: ?>
							<div class="inner">
						<? endif ?>

							<? if(@$event['special'] == 'daychange'): ?>

								<h3><?=h($event['title'])?></h3>

							<? elseif(@$event['special'] == 'gap'): ?>

								<!--h3>Gap</h3-->

							<? elseif(@$event['special'] == 'pause'): ?>

								<h3><?=h($event['title'])?></h3>

							<? else: ?>

								<h4><?=h(strftime('%H:%M', $event['start']))?>
									&ndash;
									<?=h(strftime('%H:%M', $event['end']))?>
									&nbsp;in&nbsp;
									<?=h($scheduleRoom ? $scheduleRoom->getDisplay() : $roomname) ?>
								</h4>
								<h3>
									<?=h($event['title'])?>
								</h3>
								<? if($event['speaker']): ?>
									<h5>by&nbsp;<?=h($event['speaker'])?></h5>
								<? endif ?>
							<? endif ?>

						<? if($scheduleRoom): ?>
							</a>
						<? else: ?>
							</div>
						<? endif ?>
					</div>

				<? endforeach ?>
			</div>
		<? endforeach ?>
	</div>
</div>
