<div class="schedule scroll-container">
	<div class="scroll-element">
		<? $totalWidth = round($schedule->getDurationSum() / $schedule->getScale()) ?>
		<div class="now" style="width: <?= h($totalWidth) ?>px">
			<div class="overlay"></div>
			<div class="label">now</div>
		</div>
		<? $rooms = $schedule->getSchedule() ?>
		<? foreach($rooms as $roomname => $events): ?>
			<? $scheduleRoom = $schedule->getMappedRoom($roomname) ?>
			<div class="room <? if(isset($room) && $roomname == $room->getScheduleName()): ?>highlight<? endif ?>" style="width: <?= h($totalWidth) ?>px">
				<? $fromstart = 0; ?>
				<? foreach($events as $event): ?>
					<div
						class="block <?=h(@$event['special'] ?: 'event')?> <?=h((@$event['optout']) ? 'optout' : '')?>"
						style="width: <?=h(round($event['duration'] / $schedule->getScale()))?>px; left: <?=h(round($fromstart / $schedule->getScale()))?>px"
						data-start="<?=intval($event['start'])?>"
						data-end="<?=intval($event['end'])?>"
						data-offset="<?=intval($event['offset']/60)?>"
					>
						<? $fromstart += $event['duration'] ?>
						<? if($scheduleRoom): ?>
							<a
								class="inner"
								<? if (isset($stream)): ?>
										href="<?=h($scheduleRoom->createTabObject($stream->getSelection())->getLink($roomname))?>"
								<? else: ?>
										href="<?=h($scheduleRoom->createTabObject()->getLink($roomname))?>"
								<? endif ?>
								title="Switch to <?=h($scheduleRoom->getDisplay())?>"
							>
						<? else: ?>
							<div class="inner">
						<? endif ?>

							<? if(@$event['special'] == 'daychange'): ?>

							<h3><?=h($event['title'])?></h3>

							<? elseif(@$event['special'] == 'gap'): ?>

								<!--h3>Gap</h3-->

							<? elseif(@$event['special'] == 'pause'): ?>

								<h3><?=h($event['title'])?></h3>

							<? else: ?>
								<? if($event['duration'] > 10*60): /* only display when event is longer as 10 minutes */ ?>
									<h4><?=h($event['tstart'])?>
										&ndash;
										<?=h($event['tend'])?>
										&nbsp;in&nbsp;
										<?=h($scheduleRoom ? $scheduleRoom->getDisplayShort() : $roomname) ?>
									</h4>
								<? endif ?>
								<h3 title="<?=$event['title']?>">
									<?=h($event['title'])?><? if (@$event['optout']): ?><i> (no recording)</i><? endif ?>
								</h3>
								<? if(! empty(trim($event['speaker']))): ?>
									<h5>by&nbsp;<?=h($event['speaker'])?></h5>
								<? endif ?>
							<? endif ?>

						<? if($scheduleRoom): ?>
							</a>
						<? else: ?>
							</div>
						<? endif ?>
					</div>

				<? endforeach ?>
			</div>
		<? endforeach ?>
	</div>
</div>
