<div class="schedule scroll-container">
	<div id="schedule-event-detail-popover">
		<div id="modal-content">
			<div id="modal-header">
				<h3 id="modal-title"></h3>
				<button type="button" class="close modal-close" aria-label="Close" onclick="closeEventDetails()"><span aria-hidden="true">×</span></button>
			</div>
			<div id="modal-body">
				<dl id="modal-data"></dl>
				<hr />
				<p id="modal-text"></p>
			</div>
		</div>
	</div>

	<div class="scroll-element">
		<? $totalWidth = round($schedule->getDurationSum() / $schedule->getScale()) ?>
		<div class="now" style="width: <?= h($totalWidth) ?>px">
			<div class="overlay"></div>
			<div class="label">now</div>
		</div>
		<? $rooms = $schedule->getSchedule() ?>
		<? foreach($rooms as $roomname => $events): ?>
			<? $scheduleRoom = $schedule->getMappedRoom($roomname) ?>
			<div class="room <? if(isset($room) && ($roomname == $room->getScheduleName() ||  ($scheduleRoom && $scheduleRoom->getId() === $room->getId()))): ?>highlight<? endif ?>" style="width: <?= h($totalWidth) ?>px">
				<? $fromstart = 0; ?>
				<? foreach($events as $event): ?>
					<? $special = isset($event['special']) ? $event['special'] : ''; ?>
					<? $event_is_optout = isset($event['optout']) ? $event['optout'] : false; ?>
					<? $event_guid = isset($event['guid']) ? $event['guid'] : ''; ?>
					<? $event_url = isset($event['url']) ? $event['url'] : ''; ?>
					<? $event_title = isset($event['title']) ? $event['title'] : ''; ?>
					<div
						class="block <?=h($special ?: 'event')?> <?=h($event_is_optout ? 'optout' : '')?>"
						style="width: <?=h(round($event['duration'] / $schedule->getScale()))?>px; left: <?=h(round($fromstart / $schedule->getScale()))?>px"
						data-start="<?=intval($event['start'])?>"
						data-end="<?=intval($event['end'])?>"
						data-offset="<?=intval($event['offset']/60)?>"
					>
						<? $fromstart += $event['duration'] ?>
						<? if($scheduleRoom): ?>
							<a
								class="inner"
								<? if (isset($stream)): ?>
										href="<?=h($scheduleRoom->createTabObject($stream->getSelection())->getLink($roomname))?>"
								<? else: ?>
										href="<?=h($scheduleRoom->createTabObject()->getLink($roomname))?>"
								<? endif ?>
								title="Switch to <?=h($scheduleRoom->getDisplay())?>"
								onmouseover="showEventDetails(event, {title:'<?=str_replace(array('\\', '"'), array('\\\\', '\\x22'), $event_title)?>', guid:'<?=$event_guid?>', url:'<?=$event_url?>', type:'<?=@$special?>'})"
							>
						<? else: ?>
							<div class="inner">
						<? endif ?>

							<? if(@$special == 'daychange'): ?>

							<h3><?=h($event['title'])?></h3>

							<? elseif(@$special == 'gap'): ?>

								<!--h3>Gap</h3-->

							<? elseif(@$special == 'pause'): ?>

								<h3><?=h($event['title'])?></h3>

							<? else: ?>
								<? if($event['duration'] > 10*60): /* only display when event is longer as 10 minutes */ ?>
									<h4><?=h($event['tstart'])?>
										&ndash;
										<?=h($event['tend'])?>
										&nbsp;in&nbsp;
										<?=h($scheduleRoom ? $scheduleRoom->getDisplayShort() : $roomname) ?>
									</h4>
								<? endif ?>
								<h3 title="<?=$event['title']?>">
									<?=h($event['title'])?><? if ($event_is_optout): ?><i> (no recording)</i><? endif ?>
								</h3>
								<? if(! empty(trim($event['speaker']))): ?>
									<h5>by&nbsp;<?=h($event['speaker'])?></h5>
								<? endif ?>
							<? endif ?>

						<? if($scheduleRoom): ?>
							</a>
						<? else: ?>
							</div>
						<? endif ?>
					</div>

				<? endforeach ?>
			</div>
		<? endforeach ?>
	</div>
</div>
