<? foreach($events as $event): ?>
	<div class="col-xs-10 col-xs-offset-1 col-md-6 col-md-offset-3">

		<div class="panel panel-default">
			<div class="panel-heading">
				<? if($event['description']): ?>
					<a href="<?=h($event['description'])?>">
						<?=h($event['name'])?>
					</a>
				<? else: ?>
					<?=h($event['name'])?>
				<? endif ?>
			</div>
			<div class="panel-body">
				<?=h($event['location'])?><br />
				<?=h($event['start_date'])?> – <?=h($event['end_date'])?>
			</div>
		</div>

	</div>
<? endforeach ?>
