<script type="text/javascript" src="<?=h($assets)?>clapprio/dash-shaka-playback.min.js"></script>
<script type="text/javascript" src="<?=h($assets)?>clapprio/level-selector.min.js"></script>
<script type="text/javascript" src="<?=h($assets)?>clapprio/audio-selector.min.js"></script>

<div class="dashContainer">
	<div id="player"></div>
</div>

<!--
 this is an experimental hack, trying to protect the remaining page from
 interference with the new dash-player.
-->
<script type="text/javascript">
(function(){
	// Select relay from cdn url, retry indefinitely
	var selectRelay = function(url, cb) {
		$.ajax({
			url: url,
			cache: false,
			dataType: "text",
			timeout: 3000,
			success: function(result, state, xhr) {
				var relay = xhr.getResponseHeader("X-Host");
				if (!relay)
					setTimeout(selectRelay.bind(null, url, cb), 2000);

				console.log("selected relay", relay);
				var proto = url.match(/^https?:\/\//),
					path = "/" + url.split("/").slice(3).join("/");
				cb(proto + relay + path)
			},
			error: function(err) {
				console.error("Error while selecting relay: ", err.status, err.statusText)
				setTimeout(selectRelay.bind(null, url, cb), 2000);
			}
		});
	}

	var createPlayer = function(sources) {
		return new Clappr.Player({
			sources: sources,
			width: "100%",
			plugins: [DashShakaPlayback, LevelSelector, AudioSelector],
			shakaConfiguration: {
				abr: {
					defaultBandwidthEstimate: 1000000
				},
				streaming: {
					rebufferingGoal: 12,
					jumpLargeGaps: true
				}
			},
			levelSelectorConfig: {
				labels: {
					// HLS
					0: 'Slides',
					1: 'SD',
					2: 'HD',

					// DASH
					7: 'HD',
					8: 'SD',
					9: 'Slides',
					10: 'HD',
					11: 'SD',
					12: 'Slides',
					13: 'HD',
					14: 'SD',
					15: 'Slides',
				}
			},
			autoPlay: true,
			parentId: '#player'
		});
	}

	var hasMSE = 'MediaSource' in window,
		hasWebM = document.createElement('video').canPlayType('video/webm') != "",
		nativeHLS = document.createElement('video').canPlayType('application/vnd.apple.mpegURL') != "";

	// Play Multiquality only if supported
	if (hasMSE || nativeHLS) {
		// Detect WebM capability, Select relay, Create player
		var cdnUrl = hasWebM ? '<?=h($room->getDashManifestUrl())?>' : '<?=h($room->getHLSPlaylistUrl())?>';
		selectRelay(cdnUrl, function(relayUrl) {
			createPlayer([{source: relayUrl}]);
		});
	} else {
		// Default to simple WebM playback
		var player = createPlayer([{
			source: "<?=h($stream->getVideoUrl('webm', 'hd'))?>",
			mimeType: "video/webm"
		}]);
	}
}());
</script>


<style type="text/css">
#player > [data-player] {
	padding-bottom: 56.25%;
	height: auto !important;
}
body.room .player-wrap.tab-content {
	padding: 0;
}
</style>
