<div
	style="max-width: <?=h($width)?>px; max-height: <?=h($height)?>px;"
	class="video-wrap"
	data-width="<?=h($width)?>"
	data-height="<?=h($height)?>"
	data-m3u8="<?=h(forceproto($talk['playlist']))?>"
	<? if(array_key_exists('sprites', $talk)): ?>
	data-sprites="<?= h($talk['sprites']['url']) ?>"
	data-sprites-n="<?= h($talk['sprites']['n']) ?>"
	data-sprites-cols="<?= h($talk['sprites']['cols']) ?>"
	data-sprites-interval="<?= h($talk['sprites']['interval']) ?>"
	<? endif ?>
	<? if(array_key_exists('timelens', $talk)): ?>
	data-timelens-timeline="<?= h($talk['timelens']['timeline']) ?>"
	data-timelens-thumbs="<?= h($talk['timelens']['thumbs']) ?>"
	<? endif ?>
>
</div>
