<div style="max-width: <?=h($stream->getVideoWidth())?>px; max-height: <?=h($stream->getVideoHeight())?>px;" class="video-wrap">
	<video
		<? if(!isset($autoplay) || $autoplay == true): ?>
			autoplay="autoplay"
		<? endif ?>
		preload="auto"
		width="<?=h($stream->getVideoWidth())?>"
		height="<?=h($stream->getVideoHeight())?>"
		style="width: 100%; height: 100%;"
	>
		<source
			data-plugin-type="native"
			src="<?=h($stream->getVideoUrl('webm'))?>"
			title="WebM (Icecast)"
			type="video/webm"
		/>
		<source
			data-plugin-type="native"
			src="<?=h($stream->getVideoUrl('hls'))?>"
			title="h.264 (HLS)"
			type="application/vnd.apple.mpegURL"
		/>
	</video>
</div>
