<div style="width: 100%; height: 100%; max-width: <?=h($width)?>px; margin: 0 auto;">
	<video
		autoplay="autoplay"
		preload="auto"
		width="<?=h($width)?>"
		height="<?=h($height)?>"
		style="width: 100%; height: 100%;"
		class="<?=h($miniroom ? 'nosubs' : 'subs')?>"
	>
		<source
			data-plugin-type="native"
			src="<?=h(link_stream('webm', $room, $format, $translated))?>"
			title="WebM (Icecast)"
			type="video/webm"
		/>
		<source
			data-plugin-type="flash"
			src="<?=h(link_stream('rtmp', $room, $format, $translated))?>"
			title="h.264 (RTMP)"
			type="video/rtmp"
		/>
		<source
			data-plugin-type="native"
			src="<?=h(link_stream('hls', $room, $hlsformat, $translated))?>"
			title="h.264 (HLS)"
			type="application/vnd.apple.mpegURL"
		/>
	</video>
</div>