<h3>Formats</h3>
<ul>
	<li>
		<span class="label filetype">AUDIO</span>
		<a href="<?=h(link_player($room, 'audio'))?>">
			<span class="fa fa-flag-o"></span>
			native
		</a>
		<a href="<?=h(link_player($room, 'audio', true))?>">
			<span class="fa fa-flag"></span>
			translated
		</a>
	</li>
</ul>

<hr />

<h3>Directlinks</h3>
<ul>
	<? foreach(array('mp3', 'ogg', 'opus') as $iter): ?>
		<li>
			<span class="label filetype"><?=h(strtoupper($iter))?></span>
			<a href="<?=h(link_stream('icecast', $room, $iter))?>">
				<span class="fa fa-flag-o"></span>
				native
			</a>
			<a href="<?=h(link_stream('icecast', $room, $iter, true))?>">
				<span class="fa fa-flag"></span>
				translated
			</a>
		</li>
	<? endforeach ?>
</ul>
