<div class="container-fluid">
	<? $selection = $room->createSelectionObject('audio') ?>
	<? if($room->hasTranslation()): ?>
		<h3>Audio</h3>
		<div class="formats row">

			<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
				<div class="btn-group" role="group">
					<div class="btn btn-primary" disabled>Audio</div>

					<a href="<?=h($selection->getLink())?>" class="btn btn-primary">
						<span class="fa fa-flag-o"></span>
						native
					</a>
					<a href="<?=h($selection->getTranslatedLink())?>" class="btn btn-primary">
						<span class="fa fa-flag"></span>
						translated
					</a>

				</div>
			</div>

		</div>
		<br /><br />
	<? endif ?>



	<div class="directlinks">

		<? foreach(Stream::getAudioProtos() as $proto => $display): ?>
			<h3>Direct links (<?=h($display)?>)</h3>
			<div class="row">
				<? $switcherstream = $room->createStreamObject('music') ?>
				<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
					<div class="btn-group" role="group" title="<?=h($switcherstream->getAudioTech($proto))?>">
						<div class="btn btn-primary" disabled><?=h($selection->getDisplay())?></div>
						<? if($room->hasTranslation()): ?>

							<a href="<?=h($room->createStreamObject('audio', 'native')->getAudioUrl($proto))?>" class="btn btn-default">
								<span class="fa fa-flag-o"></span>
								native
							</a>
							<a href="<?=h($room->createStreamObject('audio', 'translated')->getAudioUrl($proto))?>" class="btn btn-default">
								<span class="fa fa-flag"></span>
								translated
							</a>

						<? else: ?>

							<a href="<?=h($switcherstream->getAudioUrl($proto))?>" class="btn btn-default">
								<span class="fa fa-volume-up"></span>
								<?=h($display)?>
							</a>

						<? endif ?>
					</div>
				</div>
			</div>
		<? endforeach ?>

	</div>
</div>
