<div class="container-fluid">

	<div class="notes well">
		<h3 class="beta">WebM DASH</h3>
		<p><a href="https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP">DASH</a> is an adaptive-bitrate HTTP-based streaming solution, that is (unlike existing proprietary solutions such as HLS) internationally standardized.</p>
		<p>Support for DASH in open source software such as ffmpeg is still pretty rough, so consider this a technology-preview, it's not yet a stable solution.</p>
		<p>Please report your experience to <a href="https://twitter.com/c3voc">@c3voc</a>.</p>
	</div>


	<div class="directlinks">
		<? foreach(Stream::getVideoProtos() as $proto => $display): ?>
			<h3>Direct links (<?=h($display)?>)</h3>
			<div class="row">
				<? foreach($room->getVideoResolutions() as $res): ?>
					<? $selection = $room->createSelectionObject($res) ?>
					<? $switcherstream = $room->createStreamObject($res) ?>
					<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
						<div class="btn-group" role="group" title="<?=h($switcherstream->getVideoTech($proto))?>">
							<div class="btn btn-primary" disabled><?=h($selection->getDisplay())?></div>
							<? if($room->hasTranslation()): ?>

								<a href="<?=h($room->createStreamObject($res, 'native')->getVideoUrl($proto))?>" class="btn btn-default">
									<span class="fa fa-flag-o"></span>
									Native
								</a>
								<? foreach($room->getTranslations() as $translation): ?>
									<a href="<?=h($room->createStreamObject($res, $translation['endpoint'])->getVideoUrl($proto))?>" class="btn btn-default">
										<span class="fa fa-flag"></span>
										<?=h(ucfirst($translation['label']))?>
									</a>
								<? endforeach ?>

							<? else: ?>

								<a href="<?=h($switcherstream->getVideoUrl($proto))?>" class="btn btn-default">
									<span class="fa fa-video-camera"></span>
									Video
								</a>

							<? endif ?>
						</div>
					</div>
				<? endforeach ?>
			</div>
		<? endforeach ?>
	</div>

	<div class="directlinks">
		<h3>Direct link to DASH-Manifest</h3>

		<div class="row">
			<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">

				<div class="btn-group" role="group">
					<div class="btn btn-primary" disabled>DASH</div>
					<a href="<?=h($room->getDashManifestUrl())?>" target="_blank" class="btn btn-default">
						<span class="fa fa-flask"></span>
						Manifest
					</a>
				</div>

			</div>
		</div>
	</div>

</div>
