<h3>Formats</h3>
<ul>
	<? foreach(array('hq', 'lq') as $iter): ?>
		<li>
			<span class="label filetype"><?=h(strtoupper($iter))?></span>
			<a href="<?=h(link_player($room, $iter))?>">
				<span class="fa fa-video-camera"></span>
				live video-podcast
			</a>
		</li>
	<? endforeach ?>
</ul>

<hr />

<? foreach(array('rtmp', 'hls') as $protocol): ?>
	<h3>Directlinks (<?=h(strtoupper($protocol))?>)</h3>
	<ul>
		<? foreach(array('hq', 'lq') as $iter): ?>
			<li>
				<span class="label filetype"><?=h(strtoupper($iter))?></span>
				<a href="<?=h(link_stream($protocol, $room, $iter))?>">
					<span class="fa fa-video-camera"></span>
					live video-podcast
				</a>
			</li>
		<? endforeach ?>
	</ul>
<? endforeach ?>

<h3>Directlinks (WebM)</h3>
<ul>
	<li>
		<span class="label filetype">HQ</span>
		<a href="<?=h(link_stream('webm', $room, 'webm'))?>">
			<span class="fa fa-video-camera"></span>
			live video-podcast
		</a>
	</li>
</ul>
