<h3>Formats</h3>
<ul>
	<? foreach(array('hd', 'sd') as $iter): ?>
		<li>
			<span class="label filetype" title="<?=h(format_text($iter))?>"><?=h(strtoupper($iter))?></span>
			<a href="<?=h(link_player($room, $iter))?>">
				<span class="fa fa-flag-o"></span>
				video
			</a>
		</li>
	<? endforeach ?>
</ul>

<hr />

<? foreach(array('rtmp', 'hls') as $protocol): ?>
	<h3>Directlinks (<?=h(strtoupper($protocol))?>)</h3>
	<ul>
		<?
			if($protocol == 'hls')
				$formats = array('auto', 'hd', 'sd');
			else
				$formats = array('hd', 'sd');
		?>
		<? foreach($formats as $iter): ?>
			<li>
				<span class="label filetype" title="<?=h(format_text($iter))?>"><?=h(strtoupper($iter))?></span>
				<a href="<?=h(link_stream($protocol, $room, $iter))?>">
					<span class="fa fa-flag-o"></span>
					video
				</a>
			</li>
		<? endforeach ?>
	</ul>
<? endforeach ?>

<h3>Directlinks (WebM)</h3>
<ul>
	<? foreach(array('hd', 'sd') as $iter): ?>
		<li>
			<span class="label filetype" title="<?=h(format_text('webm'))?>"><?=h(strtoupper($iter))?></span>
			<a href="<?=h(link_stream('webm', $room, $iter))?>">
				<span class="fa fa-flag-o"></span>
				video
			</a>
		</li>
	<? endforeach ?>
</ul>
