<h3>Directlinks</h3>
<ul>
<? foreach(array('rtmp', 'hls') as $protocol): ?>
		<li>
			<span class="label filetype" title="<?=h(format_text('sd'))?>"><?=h($protocol)?></span>
			<a href="<?=h(link_stream($protocol, $room, 'sd'))?>">
				<span class="fa fa-video-camera"></span>
				live video-podcast
			</a>
		</li>
<? endforeach ?>
	<li>
		<span class="label filetype" title="<?=h(format_text('webm'))?>">WebM</span>
		<a href="<?=h(link_stream('webm', $room, 'webm'))?>">
			<span class="fa fa-video-camera"></span>
			live video-podcast
		</a>
	</li>
</ul>
