<div class="container-fluid">
	<h3>Directlinks</h3>
	<div class="directlinks">
		<div class="row">
			<? foreach(Stream::getMusicProtos() as $proto => $display): ?>
				<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
					<div class="btn-group" role="group">
						<div class="btn btn-primary" disabled><?=h($display)?></div>

						<a href="<?=h($room->createStreamObject('music')->getMusicUrl($proto))?>" class="btn btn-default">
							<span class="fa fa-music"></span>
							live music
						</a>

					</div>
				</div>
			<? endforeach ?>
		</div>
	</div>
</div>
