<div class="container-fluid">
	<h3>Directlinks</h3>
	<div class="formats row">

		<? foreach(array_intersect($formats, array('music-mp3', 'music-opus', 'music-ogg')) as $format): ?>
			<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
				<? $proto = substr($format, 6) ?>
				<div class="btn-group" role="group">
					<div class="btn btn-primary" disabled><?=h(strtoupper($proto))?></div>

						<a href="<?=h(link_stream('music', $room, $proto))?>" class="btn btn-default">
							<span class="fa fa-music"></span>
							music
						</a>

				</div>
			</div>
		<? endforeach ?>

	</div>
</div>
