<div class="container-fluid">
	<? $selection = $room->createSelectionObject('audio') ?>
	<? if($room->hasTranslation()): ?>
		<h3>Slides</h3>
		<div class="formats row">

			<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
				<div class="btn-group" role="group">
					<div class="btn btn-primary" disabled>Slides</div>

					<a href="<?=h($selection->getLink())?>" class="btn btn-default">
						<span class="fa fa-flag-o"></span>
						native
					</a>
					<a href="<?=h($selection->getTranslatedLink())?>" class="btn btn-default">
						<span class="fa fa-flag"></span>
						translated
					</a>

				</div>
			</div>

		</div>
	<? endif ?>



	<div class="directlinks">

		<? foreach(Stream::getSlidesProtos() as $proto => $display): ?>
			<h3>Direct links (<?=h($display)?>)</h3>
			<div class="row">
				<? $switcherstream = $room->createStreamObject('slides') ?>
				<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
					<div class="btn-group" role="group" title="<?=h($switcherstream->getSlidesTech($proto))?>">
						<div class="btn btn-primary" disabled><?=h($selection->getDisplay())?></div>
						<? if($room->hasTranslation()): ?>

							<a href="<?=h($room->createStreamObject('slides', 'native')->getSlidesUrl($proto))?>" class="btn btn-default">
								<span class="fa fa-flag-o"></span>
								native
							</a>
							<a href="<?=h($room->createStreamObject('slides', 'translated')->getSlidesUrl($proto))?>" class="btn btn-default">
								<span class="fa fa-flag"></span>
								translated
							</a>

						<? else: ?>

							<a href="<?=h($switcherstream->getSlidesUrl($proto))?>" class="btn btn-default">
								<span class="fa fa-picture-o"></span>
								slides
							</a>

						<? endif ?>
					</div>
				</div>
			</div>
		<? endforeach ?>

	</div>
</div>
