<div class="container-fluid">
	<? if($has_translation): ?>
		<h3>Slides</h3>
		<div class="formats row">

			<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
				<div class="btn-group" role="group">
					<div class="btn btn-primary" disabled>Slides</div>

					<a href="<?=h(link_player($room, 'slides'))?>" class="btn btn-default">
						<span class="fa fa-flag-o"></span>
						native
					</a>
					<a href="<?=h(link_player($room, 'slides', true))?>" class="btn btn-default">
						<span class="fa fa-flag"></span>
						translated
					</a>

				</div>
			</div>

		</div>
	<? endif ?>

	<h3>Directlinks</h3>
	<div class="formats row">

		<? foreach(array_intersect($protos, array('rtmp', 'hls')) as $proto): ?>
			<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
				<div class="btn-group" role="group">
					<div class="btn btn-primary" disabled><?=h(strtoupper($proto))?></div>

					<? if($has_translation): ?>

						<a href="<?=h(link_stream($proto, $room, 'slides'))?>" class="btn btn-default">
							<span class="fa fa-flag-o"></span>
							native
						</a>
						<a href="<?=h(link_stream($proto, $room, 'slides', true))?>" class="btn btn-default">
							<span class="fa fa-flag"></span>
							translated
						</a>

					<? else: ?>

						<a href="<?=h(link_stream($proto, $room, 'slides'))?>" class="btn btn-default">
							<span class="fa fa-picture-o"></span>
							slides
						</a>

					<? endif ?>

				</div>
			</div>
		<? endforeach ?>

	</div>

</div>