<h3>Formate</h3>
<ul>
	<? foreach(array('hd', 'hq', 'lq') as $iter): ?>
		<li>
			<span class="label filetype"><?=h(strtoupper($iter))?></span>
			<a href="<?=h(link_player($room, $iter))?>">
				<span class="fa fa-flag-o"></span>
				native
			</a>
			<a href="<?=h(link_player($room, $iter, true))?>">
				<span class="fa fa-flag"></span>
				translated
			</a>
		</li>
	<? endforeach ?>
</ul>

<hr />

<? foreach(array('rtmp', 'hls') as $protocol): ?>
	<h3>Direktlinks (<?=h(strtoupper($protocol))?>)</h3>
	<ul>
		<? foreach(array('hd', 'hq', 'lq') as $iter): ?>
			<li>
				<span class="label filetype"><?=h(strtoupper($iter))?></span>
				<a href="<?=h(link_stream($protocol, $room, $iter))?>">
					<span class="fa fa-flag-o"></span>
					native
				</a>
				<a href="<?=h(link_stream($protocol, $room, $iter, true))?>">
					<span class="fa fa-flag"></span>
					translated
				</a>
			</li>
		<? endforeach ?>
	</ul>
<? endforeach ?>
