<div class="container-fluid">
	<h3>Video</h3>
	<div class="formats row">

		<? foreach($room->getVideoResolutions() as $res): ?>
			<? $selection = $room->createSelectionObject($res) ?>
			<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
				<div class="btn-group" role="group">
					<div class="btn btn-primary" disabled><?=h($selection->getDisplay())?></div>

					<? if($room->hasTranslation()): ?>

						<a href="<?=h($selection->getLink())?>" class="btn btn-primary">
							<span class="fa fa-flag-o"></span>
							native
						</a>
						<a href="<?=h($selection->getTranslatedLink())?>" class="btn btn-primary">
							<span class="fa fa-flag"></span>
							translated
						</a>

					<? else: ?>

						<a href="<?=h($selection->getLink())?>" class="btn btn-primary">
							<span class="fa fa-video-camera"></span>
							video
						</a>

					<? endif ?>
				</div>
			</div>
		<? endforeach ?>

	</div>

	<div class="notes well">
		<? include("$assemblies/desktop-player.phtml") ?>
	</div>

	<div class="directlinks">
		<? foreach(Stream::getVideoProtos() as $proto => $display): ?>
			<h3>Direct links (<?=h($display)?>)</h3>
			<div class="row">
				<? foreach($room->getVideoResolutions() as $res): ?>
					<? $selection = $room->createSelectionObject($res) ?>
					<? $switcherstream = $room->createStreamObject($res) ?>
					<div class="col-lg-3 col-md-4 col-lg-5 col-xs-12">
						<div class="btn-group" role="group" title="<?=h($switcherstream->getVideoTech($proto))?>">
							<div class="btn btn-primary" disabled><?=h($selection->getDisplay())?></div>
							<? if($room->hasTranslation()): ?>

								<a href="<?=h($room->createStreamObject($res, 'native')->getVideoUrl($proto))?>" class="btn btn-default">
									<span class="fa fa-flag-o"></span>
									native
								</a>
								<a href="<?=h($room->createStreamObject($res, 'translated')->getVideoUrl($proto))?>" class="btn btn-default">
									<span class="fa fa-flag"></span>
									translated
								</a>

							<? else: ?>

								<a href="<?=h($switcherstream->getVideoUrl($proto))?>" class="btn btn-default">
									<span class="fa fa-video-camera"></span>
									video
								</a>

							<? endif ?>
						</div>
					</div>
				<? endforeach ?>
			</div>
		<? endforeach ?>
	</div>
</div>
