name: validate

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: PHP Lint
      uses: voc/PHP-Lint@v1.0.0

    - name: Check for any changed config.json files
      id: check-for-changed-configs
      uses: tj-actions/changed-files@v46
      with:
        files: |
          configs/conferences/**/config.json

    - name: Validate json files
      if: steps.check-for-changed-configs.outputs.any_changed == 'true'
      uses: dsanders11/json-schema-validate-action@v1.2.0
      with:
        schema: docs/config-schema.json
        files: configs/conferences/**/config.json
